const mapping = {
  '1Blocker': ['premium'],
  '1LemonKeepAccounts/': ['vip'],
  'AI%20Art%20Generator/': ['Unlimited Access'],
  'AIBizCard': ['Pro', 'AIBizCard.Pro.Lifetime'],
  'Airmail': ['Airmail Premium'],
  'alcohol.tracker': ['pro','drinklog_lifetime'],
  'Andyworks-calculator': ['patron'],
  'Anybox': ['pro'],
  'AppBoard': ['pro','appboard_pro_lifetime'],
  'Aphrodite': ['all'],
  'apollo': ['all'],
  'APTV': ['pro'],
  'AudioPlayer': ['Pro'],
  'Aula/': ['Pro access'],
  'Awesome%20Habits': ['premium'],
  'BlackBox': ['plus','app.filmnoir.appstore.purchases.lifetime'],
  'Blackout/': ['premium','blackout_299_lt'],
  'Blurer': ['paid_access'],
  'Budget%20Flow': ['full_access','com.fabian.hasse.haushaltsbuch.upgrade.combined'],
  'Budgetify/': ['premium','budgetify_3999_lt'],
  'CardPhoto': ['premium'],
  'ChatGPTApp': ['Advanced'],
  'Chronicling/': ['Premium'],
  'CircleTime/': ['Premium'],
  'Clipboard': ['PasteLifetime'],
  'ColorWidgets': ['pro','cw_2499_1y'],
  'Cookie': ['allaccess','app.ft.Bookkeeping.lifetime'],
  'ContractMaker': ['pro', 'com.contract.lifetime'],
  'CountDuck': ['premium', 'Lifetime'],
  'CPUMonitor': ['Pro'],
  'Currency': ['plus'],
  'Currency-Converter/': ['pro'],
  'Darkroom': ['co.bergen.Darkroom.entitlement.allToolsAndFilters'],
  'DayPoem': ['Pro Lifetime'],
  'Dedupe/': ['Pro','com.curiouscreatorsco.Dedupe.pro.lifetime.notrial.39_99'],
  'Decision': ['com.nixwang.decision.entitlements.pro'],
  'DecibelMeter/': ['Premium'],
  'Documents': ['core','com.readdle.ReaddleDocsIPad.subscription.year50_upd_user'],
  'DualApp': ['Messenger Duo & Web Tools App', 'dualweb_lifetime_plan'],
  'Duplete/': ['Pro'],
  'Echo': ['PLUS'],
  'Emphasis/': ['premium'],
  'Email%20Me': ['premium'],
  'EraseIt/': ['ProVersionLifeTime'],
  'Everlog': ['premium'],
  'FaceMa/': ['Pro access'],
  'fastdiet': ['premium'],
  'Fiery': ['premium'],
  'Fileball': ['filebox_pro'],
  'Fin': ['premium', 'com.circles.fin.premium.yearly'],
  'Finch': ['plus', 'finch_plus_yearly_new_50_usd'],
  'FinancialNote': ['category'],
  'Focused%20Work': ['Pro'],
  'FoJiCam/': ['ProVersionLifeTime'],
  'FormScanner/': ['Pro','formscanner_lifetime'],
  'Gear': ['pro', 'com.gear.app.yearly'],
  'GetFace': ['Pro access'],
  'GBA/': ['xGBA.pro'],
  'G%20E%20I%20S%20T': ['memorado_premium'],
  'GoToSleep': ['Pro'],
  'GoodThing/': ['pro','goodhappens_basic_year'],
  'Grain/': ['gold','lifetimeMembership'],
  'Grow': ['grow.pro', 'grow_lifetime'],
  'Happy%3ADays': ['pro', 'happy_999_lifetime'],
  'Haushaltsbuch': ['full_access','com.fabian.hasse.haushaltsbuch.upgrade.combined'],
  'HTTPBot': ['pro'],
  'iRead': ['vip'],
  'ImageX': ['imagex.pro.ios', 'imagex.pro.ios.lifetime'],
  'intervalFlow': ['All Access','wodtimer_lf_free'],
  'iplayTV/': ['com.ll.btplayer.12'],
  'jinduoduo_calculator': ['jinduoduoapp','mobile_vip'],
  'jizhi': ['jizhi_vip'],
  'Journal_iOS/': ['PRO'],
  'kegel': ['kegel_pro'],
  'Ledger': ['Pro', 'com.lifetime.pro'],
  'LemonKeepAccounts/': ['VIP','lm_1_1month'],
  'LiveWallpaper': ['Pro access'],
  'LockFlow/': ['unlimited_access'],
  'Locket': ['Gold'],
  'LUTCamera': ['ProVersion', 'com.uzero.funforcam.monthlysub'],
  'mark_cup/': ['premium'],
  'MetadataEditor': ['unlimited_access'],
  'MindBreathYoga/': ['lifetimeusa'],
  'mizframa': ['premium', 'mf_20_lifetime2'],
  'MOZE': ['premium'],
  'MonokaiToolkitPro': ['pro','com.monokaitoolkit.pro.forever'],
  'MoneyThings': ['Premium'],
  'MP3Tag': ['premium', 'com.musictag.www.lifetime298'],
  'multitimer_app': ['premium','timus_lt'],
  'MusicBox/': ['Premium','musicbox_2999_lifetime'],
  'MusicMate': ['premium','mm_lifetime_68_premium'],
  'My%20Jump%20Lab': ['lifetime'],
  'My%20Tim': ['Pro'],
  'MyThings': ['pro','xyz.jiaolong.MyThings.pro.infinity'],
  'nbcamera/': ['patron','com.andyworks.camera.yearlyPatron'],
  'NeatNook/': ['com.neatnook.pro','com.neatnook.pro.forever'],
  'NeonBooth': ['premium', 'neon.photobooth.magic.free_lifetime'],
  'Noto': ['pro'],
  'Notedrafts': ['pro_entitlement'],
  'Ochi': ['Pro'],
  'OffScreen': ['Entitlement.Pro'],
  'One4Wall': ['lifetime', 'lifetime_key'],
  'OneBox': ['all'],
  'OneWidget': ['allaccess'],
  'Ooga/': ['Ooga'],
  'Overdue': ['Pro'],
  'Paku': ['pro'],
  'PastePal': ['premium'],
  'PDF%20Viewer': ['sub.pro'],
  'PDF_convertor/': ['VIP', 'com.pdf.convertor.forever'],
  'Period%20Calendar': ['Premium','com.lbrc.PeriodCalendar.premium.yearly'],
  'Percento': ['premium'],
  'Photom': ['premium', 'pixelmator_photo_pro_subscription_v1_pro_offer'],
  'Photomator': ['pixelmator_photo_pro_access'],
  'PhotoMark/': ['Pro', 'com.photo.mark.forever'],
  'PhotoRoom': ['business'],
  'Photon/': ['photon.paid','photon.bundle.yearly'],
  'Pillow': ['premium'],
  'PinPaper': ['allaccess'],
  'Planny': ['premium'],
  'Pomodoro': ['Plus','com.MINE.PomodoroTimer.plus.yearly'],
  'Precious/': ['Pro'],
  'ProCamera': ['private_lightbox_entitlement&san_fran_entitlement&pro_camera_up_entitlement&procamera_full_entitlement','com.cocologics.ProCamera.Up.Yearly'],
  'Project%20Delta/': ['rc_entitlement_obscura_ultra'],
  'QingLong': ['Premium'],
  'Rats%20Project': ['PandaTracker_Premiumv2','monthly_subscription_discount_idv3'],
  'reader': ['vip2','com.valo.reader.vip2.year'],
  'Reels%20Editor': ['Unlimited Access'],
  'Rec/': ['rec.paid','rec.paid.onetime'],
  'Reflix': ['com.magicgroot.reflix.entitlements','com.magicgroot.reflix.subs.lifetime'],
  'Record2Text/': ['Pro access'],
  'ScientificCalculator': ['premium','com.simpleinnovation.calculator.ai.premium.yearly.base'],
  'ScannerPro': ['plus'],
  'ScreenRecordCase/': ['Premium'],
  'server_bee': ['Pro'],
  'SharkSMS': ['VIP','com.lixkit.diary.permanent_68'],
  'ShellBean/': ['pro','com.ningle.shellbean.subscription.year'],
  'SimpleScan/': ['premium', 'com.atlantia.SimpleScan.Purchases.Lifetime'],
  'simple-': ['patron'],
  'SleepMaster/': ['premium','sm_14999_lifetime'],
  'Spektr': ['premium'],
  'Spark': ['premium'],
  'streaks': ['patron'],
  'StepUp/': ['premium'],
  'streamer/': ['Premium'],
  'Stress': ['StressWatch Pro'],
  'Subtracky': ['premium','premium_subtracky_lifetime'],
  'Tangerine': ['Premium'],
  'Taskbit/': ['Pro'],
  'Tasks': ['Pro'],
  'tiimo': ['full_access'],
  'timetrack.io': ['atimelogger-premium-plus'],
  'To%20Me/': ['Premium'],
  'Today%20App/': ['Premium', 'TodayApp_Lifetime'],
  'TouchRetouchBasic': ['premium'],
  'totowallet': ['all', 'com.ziheng.totowallet.yearly'],
  'universal/': ['Premium','remotetv.yearly.07'],
  'Unfold': ['REDUCED_PRO_YEARLY','UNFOLD_PRO_YEARLY'],
  'UpScale': ['Pro', 'com.graz.pro.forever'],
  'UTC': ['Entitlement.Pro'],
  'vibes': ['patron'],
  'VSCO': ['pro'],
  'Wake%20Music': ['premium','com.OfflineMusic.www.lifetime198'],
  'WhiteCloud': ['allaccess','wc_pro_1y'],
  'WidgetCat': ['MiaoWidgetPro'],
  'WidgetSmith': ['Premium'],
  'Wozi': ['wozi_pro_2023'],
  'Yosum/': ['Premium'],
  'YzyFit/': ['pro', 'yzyfit_lft_v2'],
  '%E4%BA%8B%E7%BA%BF': ['pro','xyz.jiaolong.eventline.pro.lifetime'],
  '%E5%85%83%E6%B0%94%E8%AE%A1%E6%97%B6': ['plus'],
  '%E6%9F%A5%E5%A6%86%E5%A6%86': ['Pro access'],
  '%E7%9B%AE%E6%A0%87%E5%9C%B0%E5%9B%BE': ['pro'],
  '%E7%BE%8E%E5%A6%86%E6%97%A5%E5%8E%86': ['Pro access'],
  '%E8%AC%8E%E5%BA%95%E6%99%82%E9%90%98': ['Entitlement.Pro'],
  '%E8%AC%8E%E5%BA%95%E9%BB%91%E8%86%A0': ['Entitlement.Pro'],
  '%E8%A8%80%E5%A4%96%E7%AD%86%E8%A8%98/': ['Premium'],
  '%E8%BD%A6%E7%A5%A8%E7%A5%A8': ['vip+watch_vip'],
  '%57%65%62%20%56%69%64%65%6F%20%43%61%73%74': ['Premium', 'premium.regular.price']
};

var ua = $request.headers['User-Agent'] || $request.headers['user-agent'], aleo = JSON.parse($response.body), aleooo = { 'is_sandbox': false, 'ownership_type': 'PURCHASED', 'billing_issues_detected_at': null, 'period_type': 'normal', 'expires_date': '2099-01-01T00:00:00Z', 'grace_period_expires_date': null, 'unsubscribe_detected_at': null, 'original_purchase_date': '2026-01-01T00:00:00Z', 'purchase_date': '2026-01-01T00:00:00Z', 'store': 'app_store' }, aleooooo = { 'grace_period_expires_date': null, 'purchase_date': '2026-01-01T00:00:00Z', 'product_identifier': 'com.aleoo.premium.yearly', 'expires_date': '2099-01-01T00:00:00Z' }, match = Object.keys(mapping).find(key => ua.includes(key)); aleo['request_date_ms'] = '2099-09-09T01:04:17Z'; match ? ((key, product_id) => { product_id ? (aleooooo['product_identifier'] = product_id, aleo['subscriber']['subscriptions'][product_id] = aleooo) : aleo['subscriber']['subscriptions']['com.aleoo.premium.yearly'] = aleooo; aleo['subscriber']['entitlements'] = {}; key.includes('&') ? key.split('&').forEach(entitlement => { aleo['subscriber']['entitlements'][entitlement] = aleooooo; }) : aleo['subscriber']['entitlements'][key] = aleooooo; })(...mapping[match]) : (aleo['subscriber']['subscriptions']['com.aleoo.premium.yearly'] = aleooo, aleo['subscriber']['entitlements']['com.aleoo.premium.yearly'] = aleooooo); $done({ 'body': JSON.stringify(aleo) });
